### PR TITLE
Ensure from and to properties for new empty files and deleted files

### LINKED ISSUE #12: No from, to when a new empty file is in the diff
When the diff consists of an empty, and new file, the resulting object does not have `from`, `to` properties that usually are there.

To reproduce, parse this diff:

```
diff --git a/a b/a
new file mode 100644
index 0000000..e69de29
diff --git a/a.s b/a.s
new file mode 100644
index 0000000..e69de29
diff --git a/a.txt b/a.txt
new file mode 100644
index 0000000..7898192
--- /dev/null
+++ b/a.txt
@@ -0,0 +1 @@
+a
```

to get:

```
[ { chunks: [],
    deletions: 0,
    additions: 0,
    new: true,
    index: [ '0000000..e69de29' ] },
  { chunks: [],
    deletions: 0,
    additions: 0,
    new: true,
    index: [ '0000000..e69de29' ] },
  { chunks: [ [Object] ],
    deletions: 0,
    additions: 1,
    new: true,
    index: [ '0000000..7898192' ],
    from: '/dev/null',
    to: 'a.txt' }]
```

I think it makes sense for them to have `from: '/dev/null'` and `to: fileName`.

### PR DESCRIPTION
**Pull request by sungwoncho**
Fix #12.

#12 extends to deleted files. Deleted files should also have `from` and `to` fields such that: `from: fileName, to: '/dev/null'`

### CODE REVIEW

**Comment by sergeyt** [comment]
@sungwoncho thanks for PR, please address my notes

**Comment by sungwoncho** [comment]
`fileNames` is a temporary variable used inside `start` function to hold file names. e.g. `[from_file_name, to_file_name]`. Would it change anything if it were instead defined in the scope of the exported parse function?

**Comment by sungwoncho** [comment]
Why does it make more sense to move `parseFile` and `parseFileFallback` inside the exported parse function? I'll revise soon.

**Comment by sergeyt** [comment]
re fileNames: ok I found parseFile call before.
re parseFile and parseFileFallback: no need to move because I saw that fileNames is not initialized before use, my mistake. thanks for PR!

**Pull request merged**
